load("@devkitpro//:tools.bzl", "dkp_header_only_cc_library")

dkp_header_only_cc_library(
    name = "nn",
    srcs = glob([
        "**/*.h",
        "**/*.hpp",
    ]),
    visibility = ["//visibility:public"],
)