load("@devkitpro//:tools.bzl", "switch_specs_to_linker_flags")

switch_specs_to_linker_flags(
    name = "default_switch_specs",
    switch_spec = "@devkitpro_sys//:default_switch_spec_file",
    visibility = ["//visibility:public"],
)