filegroup(
    name = "smo_switch_specs",
    srcs = ["switch.specs"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "smo_switch_linker_scripts",
    srcs = glob([
        "linkerscripts/*.ld",
    ]),
    visibility = ["//visibility:public"],
)